##网易系(126/163/yeah)邮箱配置
spring:
  #邮件
  mail:
    host: smtp.163.com #发送邮件服务器
    username: slearing@163.com #发送邮件的邮箱地址
    password: TPUVTFAUJCDSOVYK #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 465 #465或者994
    from: slearing@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  #数据库
  datasource:
    url: jdbc:mysql://106.15.207.96:3306/photo?serverTimezone=UTC
    username: root
    password: 19950427sS!
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis
  redis:
    database: 0
    host: 106.15.207.96
    port: 6379
    password: slearing
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
mybatis:
    mapper-locations:
      - mapper/*.xml
server:
  servlet:
    context-path: /photo
